# you need : REST Client => https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# to make this file works
# remember : edit your hosts file : 127.0.0.1 ticketing.dev
###

POST https://ticketing.dev/api/users/signup HTTP/1.1
content-type: application/json

{
  "email": "666@deamon.hell",
  "password": "NotDead333"
}
###

POST https://ticketing.dev/api/users/signin HTTP/1.1
content-type: application/json

{
  "email": "666@deamon.hell",
  "password": "NotDead333"
}

