# you need : REST Client => https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# to make this file works
###

POST http://ticketing.dev/api/users/signup HTTP/1.1
content-type: application/json

{
  "email": "444@test.com",
  "password": 44
}