apiVersion: skaffold/v3
kind: Config

deploy:
  kubectl: {}
manifests:
  rawYaml:
    - ./infra/k8s/*

build:
  local:
    push: false # on docker hub
  artifacts:
    - image: sirharvey/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: sirharvey/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: sirharvey/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
